title: ""
description: "Academic profile, research highlights, and recent publications."
baseurl: "/lab"
url: "https://gushamilton.github.io"
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
theme: null
